service:
  name: sphere-database-functions
plugins:
  - serverless-jetpack
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-offline-scheduler
provider:
  name: aws
  runtime: nodejs10.17
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 's3:*'
      Resource: '*'
package:
  excludeDevDependencies: true
  individually: true
functions:
  verifySphere:
    handler: hooks/handler.verifySphere
    events:
      - http:
          method: post
          path: sphere/verify